[package]
name = "synapse"
version = "0.1.0"
authors = ["Luminarys <postmaster@gensok.io>"]

[workspace]
members = ["./", "./rpc/", "./sycli"]

[dependencies]
rpc = { path = "rpc" }
amy = "0.8.0"
byteorder = "1.0"
lazy_static = "*"
rand = "0.3"
ring = "0.11"
url = "1.4.0"
net2 = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
bincode = "0.8"
signal = "0.3"
slog-term = "2"
slog-async = "2"
error-chain = "0.10"
c-ares = "2"
httparse = "1.2.3"
base64 = "0.6.0"
base32 = "0.3.1"
clippy = {version = "*", optional = true}

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["serde"]

[dependencies.num]
git = "https://github.com/rust-num/num"
branch = "next"
default-features = false
features = ["bigint", "serde"]

[dependencies.slog]
version = "2"
default-features = false
features = ["max_level_debug", "release_max_level_info"]

[profile.bench]
opt-level = 3
debug = true
debug-assertions = true
panic = 'unwind'

[profile.release]
opt-level = 3
debug-assertions = false
panic = 'unwind'

[features]
default = []
autobahn = []
