[package]
name = "synapse"
version = "0.1.0"
authors = ["Luminarys <postmaster@gensok.io>"]

[dependencies]
amy = "0.8.0"
byteorder = "1.0"
lazy_static = "*"
rand = "0.3"
ring = "0.11"
url = "1.4.0"
net2 = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
bincode = "0.8"
signal = "0.3"
slog-term = "2"
slog-async = "2"
error-chain = "0.10"
c-ares = "2"
httparse = "1.2.3"

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["serde"]

[dependencies.num]
git = "https://github.com/rust-num/num"
branch = "next"
default-features = false
features = ["bigint", "serde"]

[dependencies.slog]
version = "2"
default-features = false
features = ["max_level_debug"]

[profile.bench]
opt-level = 3
debug = true
rpath = true
lto = false
debug-assertions = true
codegen-units = 1
panic = 'unwind'

[profile.release]
opt-level = 3
debug = true
rpath = true
lto = true
debug-assertions = true
codegen-units = 1
panic = 'unwind'

[features]
default = []
